.\"                                      MPS-YOUTUBE manpage
.\" (C) Copyright 2014 Zlatan Todoric <zlatan.todoric@gmail.com>,

.TH mps-youtube 1 "April 14, 2014" "mps-youtube manpage"

.SH NAME
mps-youtube \- Terminal based YouTube jukebox with playlist management

.SH DESCRIPTION
This manual page documents briefly the
.B mps-yotube
software which is based on mps, and uses YouTube as a source of content and can
play and download video as well as audio.

mps-youtube has an excellent built-in help. Once you are inside the application
just type help and hit Enter.

.SH AUTHOR
This manpage was created by Zlatan Todoric for use on Debian systems but can
be used on other as well.
